theme: jekyll-theme-hacker
title: Welcome to Jhon Smith's ePortfolio
description: I am due to graduate in January 2021 with a Computer Science degree from Southern New Hampshire University.  My focus is in Information Security.
